<?xml version="1.0"?>
<?xml-model href="http://ros.org/schema/xsd/format.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>l10_hand_control_panel</name>
  <version>0.0.1</version>
  <description>L10 Hand Control Panel - GUI for controlling 10 DOF</description>
  <maintainer email="larkume@todo.todo">larkume</maintainer>
  <license>TODO: Declaration of the license</license>

  <buildtool_depend>ament_copyright</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <buildtool_depend>ament_flake8</buildtool_depend>
  <buildtool_depend>ament_pep257</buildtool_depend>
  <buildtool_depend>python3-setuptools</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>hand_forward_kinematics</depend>
  <depend>linker_hand_description</depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
